### ISSUE TITLE
PLEASE NOTE! THIS SOFTWARE MAY **NOT** BE LICENSED FOR OPEN SOURCE.

### ISSUE THREAD

**Issue by 64bits** [tSoniq/alphasync#13]
As someone who has personally wasted time improving on this product, I will leave this here as a note of caution. The author (or someone claiming to be the author -- who seems to be MIA) of this software will issue DMCA notices and such, presumably because they do not understand their own license (yes, this happens if you dutifully include the license in your project as well).

Please re-consider contributing or forking this package until the author weighs in.

**Comment by tSoniq** [comment]
Just to re-afirm that AlphaSync is available as open source and free software.

Unfortunately I received community reports that someone had taken a copy of the software, modified the name and removed all references to its open-source nature. They were then attempting to sell the essentially unchanged application as their own work and under their exclusive copyright, in contravention of the software licences.

To ensure that this does not happen again, an official version of AlphaSync will be released on the macOS app store at no cost to the end user.

The purpose of AlphaSync, source and binaries, is to provide a fully free resource to the AlphaSmart community and I will undertake whatever is necessary to protect that.
